[general]
context=default
allowoverlap=no
udpbindaddr=0.0.0.0
tcpenable=no
tcpbindaddr=0.0.0.0
transport=udp
srvlookup=yes
qualify=yes
nat=force_rport,comedia
directmedia=no
relaxdtmf=yes
dtmfmode=rfc2833
language=ru
disallow=all
allow=ulaw
allow=alaw
allow=g722

[general_template](!)
type=friend
host=dynamic
secret=secret123
context=ivr-context
disallow=all
allow=ulaw
allow=alaw
dtmfmode=rfc2833
nat=force_rport,comedia
directmedia=no
qualify=yes

; --- SIP клиенты ---
[1001](general_template)
callerid="Test User 1" <1001>

[1002](general_template)
callerid="Test User 2" <1002>

[1003](general_template)
callerid="Test User 3" <1003>